In [4]:
import numpy as np
a = np.loadtxt("minutes_n_ingredients.csv",
                    delimiter=",",skiprows = 1, dtype=int)


In [10]:
b=a[:5]
b

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [7]:
ingsr=0
c=np.mean(a, axis = 0)#среднее значение
print(c[1].astype(int))
ingsr=c[2].astype(int)
print(ingsr)

print(np.min(a[1]))# min
print(np.min(a[2]))

print(np.max(a[1]))# max
print(np.max(a[2]))

med=np.median(a, axis=0)#медиана
print(med[1:3].astype(int))

21601
9
7
6
23891
94746
[40  9]


In [24]:
d=np.quantile(a,.75,axis = 0)
e=d[1].astype(int)
f=np.clip(a[:,1],None,65)
f

array([60, 25, 10, ..., 65,  5, 65])

In [40]:
zero=(a[:,1] == 0).sum()
a[:,1]= np.clip(a[:,1], 1, None)
print(zero)

479


In [48]:
u=np.stack((a[:,1],a[:,2]), axis=1)
u1= np.unique(u, axis=0)
print(u1.shape[0])

4183


In [49]:
u2, counts = np.unique(a[:,2], return_counts=True)
dict(zip(u2, counts))

{1: 13,
 2: 926,
 3: 2895,
 4: 5515,
 5: 7913,
 6: 9376,
 7: 10628,
 8: 10951,
 9: 10585,
 10: 9591,
 11: 8297,
 12: 6605,
 13: 4997,
 14: 3663,
 15: 2595,
 16: 1767,
 17: 1246,
 18: 790,
 19: 573,
 20: 376,
 21: 217,
 22: 161,
 23: 105,
 24: 69,
 25: 50,
 26: 28,
 27: 16,
 28: 16,
 29: 12,
 30: 12,
 31: 3,
 32: 1,
 33: 2,
 34: 1,
 35: 3,
 37: 1,
 39: 1}

In [50]:
five= np.where( a[:,2]<= 5)
new = a[five]
new

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

In [53]:
h=a[:,1]/a[:,2]
print(h.astype(int))
print(h.max())

[ 3  3  1 ...  4  1 10]
268435455.875


In [60]:
sorts =np.sort(a[:,1])[::-1]
sorts=sorts[:100]
print(sorts.sum()/100)

21518445.39


In [12]:
Q=np.where(a[:,2]<ingsr)
pers=(len(a[Q])/len(a[:,2]))*100
print(pers)

48.217
